export const ADD_INGREDIENT =  'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS = 'FETCH_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';

export const INIT_ORDER_BURGER = 'INIT_ORDER_BURGER';
export const ORDER_BURGER_START = 'ORDER_BURGER_START';
export const ORDER_BURGER_SUCCESS = 'ORDER_BURGER_SUCCESS';
export const ORDER_BURGER_FAILED = 'ORDER_BURGER_FAILED';
export const FETCH_ORDERS = 'FETCH_ORDERS';
export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILED = 'FETCH_ORDERS_FAILED';
